### ISSUE TITLE
[Feature Request] use variable name for anonymous functions assigned to a variable/const

### ISSUE THREAD

**Issue by jxn-30** [pilotpirxie/cyclomatic-complexity#4]
## Problem description

Having for example the following code:
```ts
// complexity.ts
const iAmAnArrowFunction = (a: number, b: number): number => {
    return a + b;
};

function iAmAFunction(a: number, b: number): number {
    return a + b;
}

(() => {
    const a = 1;
    const b = 2;
    console.log(iAmAnArrowFunction(a, b));
    console.log(iAmAFunction(a, b));
})();
```
then `npx cyclomatic-complexity complexity.ts` will output:
```
complexity.ts: 4 (OK)
  anonymous: 2 (OK)
  anonymous: 1 (OK)
  iAmAFunction: 1 (OK)
  global: 0 (OK)
No issues found
```

Technically this is correct, as the functions are indeed anonymous functions, however it is difficult to determine which of the complexities applies to which function, especially if your file consists of many anonymous functions.

## Feature Request / Idea for solving above mentioned problem

This feature requests asks to name anonymous functions assigned to variables/consts (such as `iAmAnArrowFunction`) by the name of this variable.
The output of `npx cyclomatic-complexity complexity.ts` would then look like this:
```
complexity.ts: 4 (OK)
  anonymous: 2 (OK)
  iAmAnArrowFunction: 1 (OK)
  iAmAFunction: 1 (OK)
  global: 0 (OK)
No issues found
```
One could argue to add a note that this function is anonymous, for example by adding a `(anonymous)` to the function name. However I don't think, this is quite necessary:
```
complexity.ts: 4 (OK)
  anonymous: 2 (OK)
  iAmAnArrowFunction (anonymous): 1 (OK)
  iAmAFunction: 1 (OK)
  global: 0 (OK)
No issues found
```

## Possible difficulties
I am not into Esprima, so I am not sure, if one could easily adjust the following line or if a more complex logic would have to be introduced (such as remembering if this is a variable/const assignment and if yes, remember the variable/const name): https://github.com/pilotpirxie/cyclomatic-complexity/blob/0d51251d84bb4c7d2161776fdf2867d3d34e3993/src/complexity.ts#L41

**Comment by pilotpirxie** [comment]
Closing as https://github.com/pilotpirxie/cyclomatic-complexity/pull/6 by @gafreax solves this problem. 

For your example, the output would be:

```
complexity.ts: 3 (OK)
  [line: 2] anonymous: iAmAnArrowFunction: 1 (OK)
  [line: 5] iAmAFunction: 1 (OK)
  [line: 8] anonymous: b: 1 (OK)
  [line: 0] global: 0 (OK)
No issues found
```
