### ISSUE TITLE
[Bug] named IIFEs are returned called `anonymous` in output 

### ISSUE THREAD

**Issue by jxn-30** [pilotpirxie/cyclomatic-complexity#5]
## Steps to reproduce
Create a file `complexity.ts` with following content:
```ts
// complexity.ts
(function iife() {
    // do stuff
})();
```
and run `npx cyclomatic-complexity@1.2.2 complexity.ts`. (`1.2.2` is current latest version)

## Expected output
```
complexity.ts: 1 (OK)
  iife: 1 (OK)
  global: 0 (OK)
No issues found
```
The function is listed with its name `iife`

## Actual output
```
complexity.ts: 1 (OK)
  anonymous: 1 (OK)
  global: 0 (OK)
No issues found
```
The function is listed as `anonymous`

**Comment by gafreax** [comment]
Hi @jxn-30, I write simple code to fix this issue, there's a open PR: https://github.com/pilotpirxie/cyclomatic-complexity/pull/6

**Comment by pilotpirxie** [comment]
Hi @gafreax thanks for the PR :) Merged. I'm closing the issue.
Feel free to create new one

**Comment by jxn-30** [comment]
Thanks for merging the PR :smiling_face_with_three_hearts: 
Are there any plans on creating a latest Release with this update (here and on npm)?

**Comment by pilotpirxie** [comment]
> Thanks for merging the PR 🥰 Are there any plans on creating a latest Release with this update (here and on npm)?

Done. 1.2.3 published https://www.npmjs.com/package/cyclomatic-complexity
